@startuml activityDiagramAuth
' skinparam DefaultTextAlignment center
skinparam ActivityFontSize 14
skinparam NoteFontSize 14
skinparam TitleFontSize 20
skinparam ArrowFontSize 16

title "Процесс авторизации пользователя в системе"

|AuthSystem|
start
partition #LightCyan EventSystem {
    :Получить и разобрать событие авторизации;

    if (Событие зарегистрировано в системе?) then (нет)
        #pink:Ошибка "Событие
        авторизации не найдено";
        stop
    else (да)
        :Выполнить авторизацию
        с помощью GameRoom;
    endif
}

|AuthSystem|
partition #LightCyan GameRoom {
    :Получены данные
        (Имя, "админ код", id Сессии)
        для авторизации;
    :Выполнить авторизацию пользователя
        через AuthSystem;
}

|AuthSystem|
:Получить (Имя, "админ код") или id Сессии;
if (Проверить данных на наличие id сессии?) then (нет)
    |AuthSystem|
    #pink:Ошибка "Нет данных для
     входа по id Сессии";
    stop
else (да)
    |ConnectedUsers|
    :Поиск по последней id Сессии в
    списке "Подключенных пользователей";
endif

|AuthSystem|
if ("Подключенный Пользователь"\n найден по последней id сессии?) then (да)
    |AuthSystem|
    :Проверить **АКТУАЛЬНУЮ** id сессию
     найденного игрока;
    if (**АКТУАЛЬНАЯ** id сессия существует ?) then (Нет)
        |AuthSystem|
        :Установить актуальною сессию
         для найденного пользователя;   
        #PaleGreen:Вернуть "Подключенного пользователя";      
        stop
    else (Существует)
        |AuthSystem|
        #pink:Ошибка "Игрок с таким
         именем уже подключен";
        stop
    endif
else (нет)
    |AuthSystem|
    :Взять "Имя" из переданных данных;
endif

|AuthSystem|
:Проверить имя;
if (Имя некорректное или отсутствует?) then (да)
    |AuthSystem|
    #pink:Ошибка "Некорректное имя";
    stop
else (нет)
    |ConnectedUsers|
    :Поиск по "Имени" в списке
    "Подключенных пользователей";
endif

|AuthSystem|
if ("Подключенный пользователь" существует?) then (да)
    |AuthSystem|
    :Проверить **АКТУАЛЬНУЮ** id сессию
     найденного игрока;
    if (**АКТУАЛЬНАЯ** id сессия существует ?) then (Нет)
        |AuthSystem|
        :Установить актуальною сессию
         для найденного пользователя;  
        #PaleGreen:Вернуть "Подключенного пользователя";
        stop
    else (Существует)
        |AuthSystem|
        #pink:Ошибка "Игрок с таким
         именем уже подключен";
        stop
    endif
else (нет)
    |ConnectedUsers|
    :Проверить есть ли место для новых
    Игроков в комнате;
    ' note left
    '     Этап регистрации пользователя
    ' end note
endif

|AuthSystem|
if (Место для нового игрока есть) then (нет)
    #pink:Ошибка "Нет свободного место
     для подключения";
    stop
else (да)
    |ConnectedUsers|
    :Создать нового 
    "Подключенного пользователя";
endif

|AuthSystem|
if (Удалось создать "Подключенного пользователя") then (нет)
    |AuthSystem|
    #pink:Ошибка "Не удалось подключиться
     к активным игрокам";
    stop
else (да)
    |ConnectedUsers|
    :Добавить в список
    "Подключенных пользователей";
endif

|AuthSystem|
if (Удалось добавить нового\n "Подключенного пользователя" в список) then (да)
    |AuthSystem|
    :Установить актуальною сессию
         для найденного пользователя;  
    #PaleGreen:Вернуть "Подключенного пользователя";
    stop
else (нет)
    |AuthSystem|
    #pink:Ошибка "Не удалось добавить игрока";
    stop
endif
@enduml