@startuml sequenceDiagramsGeneral1
title Основной сценарий: __ПЕРВЫЙ__ вход в игру и начало взаимодействия

actor Клиент as client
participant Сервер as server #00dac7
participant WebSocket #65d3ff

autonumber
==Переход на сайт==
client -> server ++ #00dac7 : Переход на главную страницу / сайт
server -> server ++-- #005500 : событие: Загрузка главной страницы
alt#Gold #ebffdd Если существует событие
    server -> server ++-- #d6d300 : Подготовка страницы "Входа"
    server --> client : Возврат страницы "Входа"
else #ffeeee Если событие не найдено
    autonumber 3
    server -->> client !! : Возврат, кода ошибки\n отсутствия указанного события
    deactivate server
    |||
end

|||
client ->> WebSocket ++ #65d3ff : Установка соединения
alt#Gold #ebffdd Если существует событие
    WebSocket -->> client : Подтверждение успешного подключения

    == Действие пользователя (не связанное с игрой) ==
    client ->> WebSocket : Попытка авторизации
    WebSocket -> WebSocket ++-- #005500 : Вызов события
    WebSocket -> WebSocket ++-- #d6d300 : Авторизация пользователя как игрока
    WebSocket -> WebSocket ++-- #d6d300 : Подготовка страницы "Игровая комната"
    WebSocket -->> client -- : Возврат страницы "Игровая комната"
    |||
    == Игровой ход ==
    client ->> WebSocket ++ #65d3ff : Игровой ход
    WebSocket -> WebSocket ++-- #005500 : Вызов события
    WebSocket -> WebSocket ++-- #d6d300 : Обработка хода

    opt#Gold Если есть ответ
        WebSocket -->> client : Ответ, если есть
        |||
    end
else #ffeeee Если событие не найдено
    autonumber 5
    WebSocket -->> client !! : Возврат, кода ошибки\n отсутствия указанного события
    deactivate WebSocket
    |||
end
@enduml