@startuml sequenceDiagramGameComponents
title Детальный сценарий: взаимодействие клиента с игровыми компонентами

actor ActiveClient
actor OtherClients
participant EventSystem
participant GameRoom
participant GameHandler
participant GameSession
' participant Card
' participant Player

== Вход в игру ==
ActiveClient -[#red]> EventSystem ++ : событие: Авторизация игрока
EventSystem -> GameRoom --++ : Авторизация игрока
GameRoom -> GameRoom ++-- #d6d300 : Обработка данных
GameRoom -> GameSession ++ : Обновление или добавление игрока
GameSession --> GameRoom -- : Подтверждение добавления игрока

alt#Gold #LightBlue Если код доступа админа верный
    GameRoom -> GameRoom ++-- #d6d300 : Дать админ права
else Если код доступа админа неверный
    GameRoom --[#red]>> ActiveClient : Вернуть ошибку
    deactivate GameRoom
    |||
end

GameRoom -> GameHandler ++ : Получить последние данные
activate GameRoom
deactivate GameRoom
GameHandler --[#red]>> ActiveClient : Вернуть данные
GameHandler -->> OtherClients -- : Обновить данные о Новом игроке
|||
== Начало Игры ==
ActiveClient -[#red]> EventSystem ++ : событие: Начать игру
EventSystem -> GameRoom --++ : Проверка пользователя как\n существующего игрока
GameRoom -> GameRoom ++-- #d6d300 : Проверка кода доступа админа

opt#Gold #LightBlue Если код доступа админа - **НЕ** верный
    GameRoom --[#red]>> ActiveClient : Вернуть ошибку
    deactivate GameRoom
    |||
end

GameRoom -> GameSession ++ : проверить существование игрока
activate GameRoom
GameSession --> GameRoom -- : Игрок найден / не найден
GameRoom -> GameHandler --++ : (Передача) события: Начать игру

GameHandler -> GameSession ++ : Получить данные о состоянии игры
GameSession --> GameHandler -- : Возвращает данные о состоянии игры
GameHandler -> GameHandler ++-- #d6d300 : Проверка начало игры

GameHandler -> GameSession ++ : Проверка допустимого\n количества игроков
GameSession --> GameHandler -- : Возвращает допустимое\n количество игроков
GameHandler -> GameSession ++ : Инициализация и генерация\n идентификатора сессии
GameSession --> GameHandler -- : Возвращает идентификатор сессии
GameHandler -> GameSession ++ : Получить игровые данные\n(Колоду карт, игровое поле и тд.)
GameSession --> GameHandler -- : Возвращает запрашиваемые\n игровые данные
|||
GameHandler -> GameHandler ++-- #d6d300 : Определить роли игрокам
GameHandler --> GameSession ++ : Сохранить роли для игрока
GameSession --> GameHandler -- : Результат сохранения

GameHandler -> GameHandler ++-- #d6d300 : Определение последовательности\n ходов игроков. Шериф должен\n ходить первый
GameHandler --> GameSession ++ : Сохранить последовательность ходов для игрока
GameSession --> GameHandler -- : Результат сохранения

GameHandler -> GameHandler ++-- #d6d300 : Определяет расстояния между игроками
GameHandler --> GameSession ++ : Сохранить расстояния между игроками
GameSession --> GameHandler -- : Результат сохранения
|||
== Подготовка: выбор персонажей ==

loop#Gold #LightBlue Для каждого игрока
    GameHandler -> GameHandler ++-- #d6d300 : Назначить активного игрока на текущий раунд
    GameHandler -> GameHandler ++-- #d6d300 : Определить невыбранных персонажей для игрока

    GameHandler -->> OtherClients : Список доступных персонажей
    GameHandler --[#red]>> ActiveClient : Список доступных персонажей + сообщить игроку что он активный
    deactivate GameHandler

    ActiveClient -[#red]> EventSystem ++ : событие: Выбрал персонажа
    EventSystem -> GameRoom --++ : Проверка пользователя как\n существующего игрока
    GameRoom -> GameSession ++ : Проверить существование игрока
    GameSession --> GameRoom -- : Игрок найден / не найден
    GameRoom -> GameHandler --++ : (Передача) события: Выбрал персонажа

    GameHandler -> GameSession ++ : Получить данные о состоянии игры
    GameSession --> GameHandler -- : Возвращает данные о состоянии игры
    GameHandler -> GameHandler ++-- #d6d300 : Обработка ожидаемого события

    GameHandler -> GameHandler ++-- #d6d300 : Проверка на активного персонажа
    GameHandler -> GameHandler ++-- #d6d300 : Переопределяет доступных\n персонажей с учетом выбранного
    GameHandler --> GameSession ++ : Сохранить выбранного персонажа\n для игрока
    GameSession --> GameHandler -- : Результат сохранения
    GameHandler -->> OtherClients : Сообщает о выбранном персонаже
    GameHandler --[#red]>> ActiveClient : Сообщает о выбранном персонаже
    |||
end

|||
== Подготовка: раздача карт ==

GameHandler -> GameSession ++ : Получить список всех игроков
GameSession --> GameHandler -- : Возвращает список

GameHandler -> GameHandler ++-- #d6d300 : Обработка раздачи карт каждому игроку
GameHandler -> GameSession ++ : Обновить данные игроков и колоды
GameSession --> GameHandler -- : Подтверждение обновления

GameHandler -->> OtherClients : Вернуть данные всем игрокам

|||
== Ход игры ==

loop#Gold #LightBlue Пока партия не завершена
    GameHandler -> GameHandler ++-- #d6d300 : Назначить активного игрока на текущий раунд

    note right of GameHandler
        **1. Набор:**
    end note

    GameHandler -> GameSession ++ : Получить данные для фазы Набора\n(основная колода и сброса)
    GameSession --> GameHandler -- : Возвращает данные

    GameHandler -> GameHandler ++-- #d6d300 : Обработка фазы набора

    GameHandler -->> OtherClients : Передать данные игрокам + Кто сейчас ходит
    GameHandler --[#red]>> ActiveClient : Данные активному игроку + Его ход

    note right of GameHandler
        **2. Розыгрыш:**
    end note

    loop#Gold #LightGoldenRodYellow Пока не событие: окончание хода
        ActiveClient -[#red]> EventSystem ++ : событие: Карточный ход\n или Окончание хода
        EventSystem -> GameRoom --++ : Проверка игрока
        GameRoom -> GameSession ++ : Проверить существование игрока
        GameSession --> GameRoom -- : Игрок найден / не найден
        GameRoom -> GameHandler -- : (Передача) события: Карточный ход\n или Окончание хода

        GameHandler -> GameSession ++ : Получить данные о состоянии игры
        GameSession --> GameHandler -- : Возвращает данные

        GameHandler -> GameHandler ++-- #d6d300 : Обработка ожидаемого события
        GameHandler -> GameHandler ++-- #d6d300 : Проверка на активного персонажа
        GameHandler -> GameHandler ++-- #d6d300 : Обработка хода

        alt#Gold #LightCyan Успешная обработка
            GameHandler -> GameSession ++ : Получить актуальные данные игрока / сессии
            ' activate GameHandler
            GameSession --> GameHandler -- : Возвращает актуальные данные

            GameHandler -->> OtherClients : Обновить состояние игры
            GameHandler --[#red]>> ActiveClient : Подтверждение + новые данные
        else #LightYellow Ошибка обработки
            GameHandler --[#red]>> ActiveClient : Ошибка + последние актуальные данные
        end

        opt#Gold #LightBlue Если условие завершении игры были выполнены
            GameHandler -> GameHandler ++-- #d6d300 : Завершить игру
            GameHandler -> GameSession ++ : Обновить данные состояния игры
            GameSession -->> GameHandler -- : Результат обновления
            deactivate GameHandler
            |||
        end

        note right of GameHandler
            **3. Сброс** (при необходимости)
        end note

        GameHandler -->> OtherClients : Сообщить об этапе сброса
        activate GameHandler
        GameHandler --[#red]>> ActiveClient : Сообщить об этапе сброса

        ActiveClient -[#red]> EventSystem ++ : событие: Карты для сброса
        EventSystem -> GameRoom --++ : Проверка игрока
        GameRoom -> GameSession ++ : Проверить существование игрока
        GameSession --> GameRoom -- : Игрок найден / не найден
        GameRoom -> GameHandler -- : (Передача) события: Карты для сброса

        GameHandler -> GameSession ++ : Получить данные о состоянии игры
        GameSession --> GameHandler -- : Возвращает данные

        GameHandler -> GameHandler ++-- #d6d300 : Обработка ожидаемого события
        GameHandler -> GameHandler ++-- #d6d300 : Проверка на активного персонажа
        GameHandler -> GameHandler ++-- #d6d300 : Обработка фазы сброса

        deactivate GameHandler
    end
    |||
end

deactivate GameHandler
|||
@enduml
