@startuml useCaseDiagramGame
actor Админ as Admin
actor Пользователь as User
actor Игрок as Player

User --> (Авторизоваться как Игрок)
User --> (Авторизоваться как Админ)

(Авторизоваться как Игрок) ..> (Ввести имя) : <<include>>
(Авторизоваться как Админ) ..> (Ввести имя) : <<include>>
(Авторизоваться как Админ) ..> (Ввести код администратора) : <<include>>

Admin -|> Player
Admin --> (Начать игру)

Player --|> User
Player --> (Выбрать персонажа)
Player --> (Карточный ход)
Player --> (Окончание карточного хода)
Player --> (Сбросить карты)
@enduml