@startuml activity_behavioral_auth_player_admin
title Диаграмма активности (поведенческого типа):\n процесс авторизации игрока и администратора

start

:Ввод имени пользователя;

if (Введён код администратора?) then (да)
  :Ввод кода администратора;
  if (Код верный?) then (да)
    :Назначить роль Админа;
  else (нет)
    #pink:Показать ошибку кода;
    stop
  endif
else (нет)
  :Назначить роль Игрока;
endif

:Переход к следующему этапу игры;

stop
@enduml
