@startuml activity_behavioral_game_start_admin
title Диаграмма активности (поведенческого типа): запуск игры администратором

start

:Отправил команду "Начать игру";
:Узнать является пользователем зарегистрированным игроком;
if (Пользователь является игроком ?) then (да)
  :Проверить на админ-права;
else (нет)
  #pink:Показать ошибку на то что пользователь не игрок;
  stop
endif

if (Если у игрока админ-права) then (да)
  :Проверить админ-код на корректность;
else (нет)
  #pink:Показать ошибку на отсутствия прав администратора;
  stop
endif

if (Админ-код правильный ?) then (да)
  :Запустить игру;
else (нет)
  #pink:Показать ошибку что админ-код не корректный;
  stop
endif

stop
@enduml
